---
language: php

dist: trusty

sudo: false

os:
  - linux
#  - osx

env:
  - BEHAT_TAGS="~@slow"
  - BEHAT_TAGS="@slow"

install:
  - make behat

script:
  - . scripts/hacking.sh
  - behat --tags="~@disabled&&~@wip&&$BEHAT_TAGS"
