---
language: php

dist: trusty

sudo: false

os:
  - linux
#  - osx

addons:
  apt:
    packages:
    - python-pip

env:
  - BEHAT_TAGS="~@slow"
  - BEHAT_TAGS="@slow"

install:
  - make behat
  - pip install --user files/ansible/requirements.txt

script:
  - . scripts/hacking.sh
  - behat --tags="~@disabled&&~@wip&&$BEHAT_TAGS"
