---
language: php

dist: trusty

sudo: false

os:
  - linux
  - osx

env:
  - BEHAT_TAGS="~@slow&&~@disabled&&~@wip"
  - BEHAT_TAGS="@slow&&~@disabled&&~@wip"

install:
  - make behat

script:
  - . scripts/hacking.sh
  - behat --tags=$BEHAT_TAGS
