---
language: php

dist: trusty

sudo: false

env:
  - BEHAT_TAGS="~@slow&&~@disabled&&~@wip"
  - BEHAT_TAGS="@slow"

install:
  - make behat

script:
  - . scripts/hacking.sh
  - behat --tags=$BEHAT_TAGS
